# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9991:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  mongoweb:
    image: mongoclient/mongoclient
    depends_on:
      - mongo
    environment:
      - MONGO_URL='mongodb://mongo:27017/'
    ports:
      - 9992:3000

  grafana:
    image: grafana/grafana
    user: "1000"
    volumes:
      - ./grafana-db:/var/lib/grafana
    ports:
      - 9993:3000
